"""make_rts_fields_nullable

Revision ID: 039e129b7d08
Revises: 596409483d0a
Create Date: 2026-03-04 22:06:13.385322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e129b7d08'
down_revision: Union[str, None] = '596409483d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_version', schema=None) as batch_op:
        batch_op.alter_column('rts_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rts_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_version', schema=None) as batch_op:
        batch_op.alter_column('rts_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('rts_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
