"""initial schema

Revision ID: 596409483d0a
Revises: None
Create Date: 2026-03-04 19:00:02.227714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596409483d0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('inbox', 'refined', 'testing', 'paper_trading', 'deployed', 'paused', 'rejected', 'retired', name='strategystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.Enum('image', 'pdf', 'url', 'screenshot', 'other', name='attachmenttype'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('idea', 'hypothesis', 'observation', 'ai_summary', 'other', name='notetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rts_file_path', sa.String(), nullable=False),
    sa.Column('rts_sha256', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'rts_sha256', name='uix_strategy_sha')
    )
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('is_in_sample', sa.Boolean(), nullable=True),
    sa.Column('sample_split_date', sa.Date(), nullable=True),
    sa.Column('parameter_hash', sa.String(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_note', sa.Text(), nullable=True),
    sa.Column('equity_curve_path', sa.String(), nullable=True),
    sa.Column('trade_log_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['backtest_run.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['strategy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('html_report', 'equity_image', 'drawdown_image', 'tearsheet', 'other', name='artifacttype'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('compound_return', sa.Float(), nullable=True),
    sa.Column('rate_of_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('mar', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('pct_wins', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('win_length', sa.Float(), nullable=True),
    sa.Column('loss_length', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('avg_exposure', sa.Float(), nullable=True),
    sa.Column('max_exposure', sa.Float(), nullable=True),
    sa.Column('custom_metrics_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_metrics')
    op.drop_table('run_artifact')
    op.drop_table('backtest_run')
    op.drop_table('strategy_version')
    op.drop_table('research_note')
    op.drop_table('attachment')
    op.drop_table('universe')
    op.drop_table('strategy')
    op.drop_table('pipeline_status')
    # ### end Alembic commands ###
