"""Add Phase 5 advanced metrics and models

Revision ID: 6ab6d15a99b8
Revises: 3a9e0e5c07eb
Create Date: 2026-03-06 09:25:08.175840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab6d15a99b8'
down_revision: Union[str, None] = '3a9e0e5c07eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Enum('trade', 'note', 'performance_update', 'issue', name='deploymententrytype'), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('live_equity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walk_forward_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walk_forward_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('window_number', sa.Integer(), nullable=False),
    sa.Column('is_run_id', sa.Integer(), nullable=True),
    sa.Column('oos_run_id', sa.Integer(), nullable=True),
    sa.Column('is_start', sa.Date(), nullable=False),
    sa.Column('is_end', sa.Date(), nullable=False),
    sa.Column('oos_start', sa.Date(), nullable=False),
    sa.Column('oos_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['is_run_id'], ['backtest_run.id'], ),
    sa.ForeignKeyConstraint(['oos_run_id'], ['backtest_run.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['walk_forward_study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walk_forward_window')
    op.drop_table('walk_forward_study')
    op.drop_table('deployment_entry')
    # ### end Alembic commands ###
