"""make notes and attachments nullable add tags

Revision ID: c3a829abb550
Revises: 249fe7ecbd3c
Create Date: 2026-03-05 21:14:05.579949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a829abb550'
down_revision: Union[str, None] = '249fe7ecbd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.alter_column('strategy_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('research_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.alter_column('strategy_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('backtest_run', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_run_run_date')

    with op.batch_alter_table('run_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_run_metrics_cagr')
        batch_op.drop_index('ix_run_metrics_max_drawdown')
        batch_op.drop_index('ix_run_metrics_sharpe')

    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_status', ['status'], unique=False)

    with op.batch_alter_table('run_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_run_metrics_sharpe', ['sharpe'], unique=False)
        batch_op.create_index('ix_run_metrics_max_drawdown', ['max_drawdown'], unique=False)
        batch_op.create_index('ix_run_metrics_cagr', ['cagr'], unique=False)

    with op.batch_alter_table('research_note', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.alter_column('strategy_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('backtest_run', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_run_run_date', ['run_date'], unique=False)

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.alter_column('strategy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
